### ISSUE TITLE
Update to latest GH actions and Node version to LTS / 20

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/juno-action#3]
### Documentation

It would be nice to bump the actions (e.g. `actions/setup-node@v3` -> `actions/setup-node@v4` etc.) and Node version from 18 to 20 in the [README](https://github.com/junobuild/juno-action/blob/main/README.md) of this repo but, on the [website](https://juno.build/docs/miscellaneous/github_actions) as well.

**Comment by MukulKolpe** [comment]
Hey @peterpeterparker, can I work on this issue?

**Comment by peterpeterparker** [comment]
Sure go for it @MukulKolpe!
