### ISSUE TITLE
What should I do if error exist like:

### ISSUE THREAD

**Issue by f33r0** [junobuild/juno-action#5]
`Your terminal is not authenticated. Would you like to log in now? › no / yes`

**Comment by peterpeterparker** [comment]
There can be various reasons, let's try to figure out which.

Do you have a `juno.config` (.ts | .mjs | .json) at the root of your project?

If you project is open source, feel free to share a link to the repo.

**Comment by peterpeterparker** [comment]
It worked out @f33r0 ?
