### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by mars-area** [junobuild/juno-action#6]
Hi, there

I'm trying to use GitHub action to deploy my app, then I got this on step 5. All steps are successful except step 5.

"Cannot proceed deployment."
"Are you sure the folder containing your built app (the "source" tag in the configuration file for Juno) files is correctly configured, or have you built your app?"

Is anyone experiencing the same thing?

![image](https://github.com/user-attachments/assets/d3eb39d8-9138-45fa-a791-619095acab6d)

**Comment by peterpeterparker** [comment]
Hi @mars-area , it either a bug (which I'll obviously fix) or an issue with the configuration. Your repo is open source, can I have a quick look?

**Comment by mars-area** [comment]
I follow [this guide](https://juno.build/docs/guides/github-actions). Please take a look at this [repo](https://juno.build/docs/guides/github-actions)

**Comment by peterpeterparker** [comment]
Thanks. I provided two PRs to your repo that should help:

1. There was a typo in the usage of the environment variable: https://github.com/Paper-Line/on-chain-medical-record/pull/1

2. The config should contains your satellite ID: https://github.com/Paper-Line/on-chain-medical-record/pull/2

Can you have a look, merge the two PRs, edit afterwards your effective satellite ID and give it a try again?

**Comment by mars-area** [comment]
I identified the issue in the `juno.config.ts` file. It needs to be configured to source from the Next.js build folder, which in my case is named `out`.

Thanks for the PRs, really appreciate it. I will merge them after the hackathon. I am concerned that this may affect the judgment.

1 question, is it okay to expose the satellite id?

**Comment by peterpeterparker** [comment]
> 1 question, is it okay to expose the satellite id?

It's fine, it's a public ID.

Ping me anytime and keep me posted.
